# Database connection settings
#?????: ?????? admin ? ??? ??????? ??????. ? ???????? ??????? ?????? ??????? ?? ?????? ? ????
db.url=jdbc:postgresql://localhost:5432/otp_service
db.username=postgres
db.password=admin